### ISSUE TITLE
내 정보 수정 페이지

### ISSUE THREAD

**Issue by devmelonlee** [ncp7-team2/show_pet#28]
- 소개글에서 textarea 영역에 아무 값도 넣지 않고 회원정보 변경 시 소개글에 빈값이 넘어감.
- 프로필 사진 수정 시 헤더에 바로 반영이 되지 않아 member컨트롤러에 update부분에 세션을 다시 생성하여 프로필 수정시 사진이 바로 반영되게 하였지만
- 다시 프로필 사진을 아무 값도 넣지 않고 회원정보 변경시 다른곳은 사진이 원래 사진으로 정상적으로 나오나 헤더에 기본 이미지 사진으로 변경됩니다..

**Comment by wooni89** [comment]
이슈사항 수정했습니다~

**Comment by devmelonlee** [comment]
네 닫도록 하겠습니다
